import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import type { Contact, Transaction } from "./types"
import { formatINR, formatGoldWeight } from "./utils-finance"

export function generatePDF(contact: Contact, transactions: Transaction[]): jsPDF {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Letterhead
  doc.setFontSize(20)
  doc.setFont("helvetica", "bold")
  doc.text("HISAB / હિસાબ", pageWidth / 2, 20, { align: "center" })

  doc.setFontSize(12)
  doc.setFont("helvetica", "normal")
  doc.text("Financial Ledger / નાણાકીય ખાતાવહી", pageWidth / 2, 28, { align: "center" })

  // Contact info
  doc.setFontSize(12)
  doc.text(`Name / નામ: ${contact.name}`, 14, 45)
  doc.text(`Phone / ફોન: ${contact.phone}`, 14, 52)
  doc.text(`Date / તારીખ: ${new Date().toLocaleDateString("en-IN")}`, 14, 59)

  // Separate cash and gold transactions
  const cashTransactions = transactions.filter((t) => t.type === "cash")
  const goldTransactions = transactions.filter((t) => t.type === "gold")

  let yPosition = 70

  // Cash transactions table
  if (cashTransactions.length > 0) {
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.text("Cash Transactions / રોકડ વ્યવહારો", 14, yPosition)

    const cashData = cashTransactions.map((t) => [
      t.date,
      t.description,
      t.direction === "given" ? formatINR(t.amount) : "-",
      t.direction === "received" ? formatINR(t.amount) : "-",
    ])

    const cashBalance = cashTransactions.reduce((sum, t) => {
      return sum + (t.direction === "given" ? t.amount : -t.amount)
    }, 0)

    autoTable(doc, {
      startY: yPosition + 5,
      head: [["Date / તારીખ", "Description / વર્ણન", "Given / આપેલ", "Received / મળેલ"]],
      body: cashData,
      foot: [
        [
          "",
          "Balance / બાકી",
          cashBalance >= 0 ? formatINR(cashBalance) : "-",
          cashBalance < 0 ? formatINR(Math.abs(cashBalance)) : "-",
        ],
      ],
      styles: { fontSize: 10 },
      headStyles: { fillColor: [66, 66, 66] },
      footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: "bold" },
    })

    yPosition = (doc as any).lastAutoTable.finalY + 15
  }

  // Gold transactions table
  if (goldTransactions.length > 0) {
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.text("Gold Transactions / સોનાના વ્યવહારો", 14, yPosition)

    const goldData = goldTransactions.map((t) => [
      t.date,
      t.description,
      t.grossWeight ? `${t.grossWeight}g @ ${t.purity}%` : "-",
      t.direction === "given" ? formatGoldWeight(t.amount) : "-",
      t.direction === "received" ? formatGoldWeight(t.amount) : "-",
    ])

    const goldBalance = goldTransactions.reduce((sum, t) => {
      return sum + (t.direction === "given" ? t.amount : -t.amount)
    }, 0)

    autoTable(doc, {
      startY: yPosition + 5,
      head: [["Date / તારીખ", "Description / વર્ણન", "Gross @ Purity", "Given / આપેલ", "Received / મળેલ"]],
      body: goldData,
      foot: [
        [
          "",
          "",
          "Net Balance / ચોખ્ખું બાકી",
          goldBalance >= 0 ? formatGoldWeight(goldBalance) : "-",
          goldBalance < 0 ? formatGoldWeight(Math.abs(goldBalance)) : "-",
        ],
      ],
      styles: { fontSize: 10 },
      headStyles: { fillColor: [184, 134, 11] },
      footStyles: { fillColor: [255, 248, 220], textColor: [0, 0, 0], fontStyle: "bold" },
    })
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setFontSize(10)
  doc.setFont("helvetica", "italic")
  doc.text("Final Balance / અંતિમ બાકી", pageWidth / 2, pageHeight - 20, { align: "center" })
  doc.text("Generated by Hisab App", pageWidth / 2, pageHeight - 12, { align: "center" })

  return doc
}

export function getFileName(contactName: string): string {
  const date = new Date()
  const formattedDate = `${date.getDate().toString().padStart(2, "0")}-${(date.getMonth() + 1).toString().padStart(2, "0")}-${date.getFullYear()}`
  return `Hisab_${contactName.replace(/\s+/g, "_")}_${formattedDate}.pdf`
}

export async function sharePDF(doc: jsPDF, fileName: string): Promise<void> {
  const blob = doc.output("blob")
  const file = new File([blob], fileName, { type: "application/pdf" })

  if (navigator.share && navigator.canShare({ files: [file] })) {
    await navigator.share({
      files: [file],
      title: "Hisab Ledger",
      text: "Financial ledger statement",
    })
  } else {
    // Fallback: download
    doc.save(fileName)
  }
}
